-- MySQL Script generated by MySQL Workbench
-- Qui 30 Abr 2015 17:20:57 BRT
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema zapserver
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `zapserver` ;
CREATE SCHEMA IF NOT EXISTS `zapserver` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `zapserver` ;

-- -----------------------------------------------------
-- Table `zapserver`.`Servidor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zapserver`.`Servidor` ;

CREATE TABLE IF NOT EXISTS `zapserver`.`Servidor` (
  `jidServidor` VARCHAR(80) NOT NULL,
  `dataHoraUltimoEnvio` DATETIME NULL,
  `totalMensagensEnviadas` INT NULL,
  `dataHoraUltimoRecebimento` DATETIME NULL,
  `jidSuporte` VARCHAR(200) NULL,
  `mensagemSuporte` VARCHAR(200) NULL,
  `dataHoraAvisoSuporte` DATETIME NULL,
  `status` VARCHAR(20) NULL,
  `nomeRobo` VARCHAR(200) NULL,
  PRIMARY KEY (`jidServidor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zapserver`.`Queue`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zapserver`.`Queue` ;

CREATE TABLE IF NOT EXISTS `zapserver`.`Queue` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `jidServidor` VARCHAR(200) NULL,
  `jidCliente` VARCHAR(200) NULL,
  `url` VARCHAR(1000) NULL,
  `mensagem` TEXT NULL,
  `dados` LONGBLOB NULL,
  `imageLabel` VARCHAR(200) NULL,
  `extensao` VARCHAR(10) NULL,
  `status` VARCHAR(1) NULL,
  `dataHora` DATETIME NULL,
  `dataHoraParaEnviar` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zapserver`.`Image`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zapserver`.`Image` ;

CREATE TABLE IF NOT EXISTS `zapserver`.`Image` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `jidServidor` VARCHAR(200) NULL,
  `label` VARCHAR(1000) NULL,
  `mimeType` VARCHAR(45) NULL,
  `fileHash` VARCHAR(100) NULL,
  `fileName` VARCHAR(500) NULL,
  `url` VARCHAR(1000) NULL,
  `ip` VARCHAR(45) NULL,
  `size` INT NULL,
  `encoding` VARCHAR(20) NULL,
  `width` INT NULL,
  `height` INT NULL,
  `preview` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zapserver`.`Log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zapserver`.`Log` ;

CREATE TABLE IF NOT EXISTS `zapserver`.`Log` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `jidServidor` VARCHAR(200) NULL,
  `jidCliente` VARCHAR(200) NULL,
  `url` VARCHAR(1000) NULL,
  `mensagem` TEXT NULL,
  `status` VARCHAR(1) NULL,
  `dataHora` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
